# Generated by Django 6.0.3 on 2026-05-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_avis_prestataire_reservation_prestataire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('terminee', 'Terminée'), ('expiree', 'Expirée'), ('refusee', 'Refusée')], default='en_attente', max_length=20),
        ),
    ]
