# Generated by Django 6.0.3 on 2026-04-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_adresse_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='note_moyenne',
            field=models.FloatField(default=0.0),
        ),
    ]
